import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/api/client";
import { PageHeader } from "@/components/admin/page-header";
import { Palette, Plus, Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";
export const Route=createFileRoute("/brands")({component:BrandsPage});
function BrandsPage(){const qc=useQueryClient();const [edit,setEdit]=useState<any>(null);const [open,setOpen]=useState(false);const q=useQuery({queryKey:["admin-brands"],queryFn:async()=>{const r=await api.get("/admin/brands");return r.data?.data??r.data??[];}});const remove=useMutation({mutationFn:(id:string)=>api.delete(`/admin/brands/${id}`),onSuccess:()=>{toast.success("Brand disabled");qc.invalidateQueries({queryKey:["admin-brands"]});}});return <><PageHeader title="Brands" icon={<Palette className="h-5 w-5"/>} breadcrumbs={[{label:"Dashboard",to:"/"},{label:"Brands"}]} actions={<button onClick={()=>{setEdit(null);setOpen(true)}} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground"><Plus className="h-4 w-4"/>Add Brand</button>}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(q.data||[]).map((b:any)=><div key={b.id||b._id} className="rounded-2xl border bg-card p-4 shadow-card"><img src={b.imageUrl||b.image} alt={b.name} className="h-28 w-full rounded-xl bg-muted object-contain"/><div className="mt-3 font-bold">{b.name}</div><div className="text-xs text-muted-foreground">/{b.slug}</div><div className="mt-3 flex gap-2"><button onClick={()=>{setEdit(b);setOpen(true)}} className="rounded-lg border p-2"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove.mutate(String(b.id||b._id))} className="rounded-lg border p-2 text-destructive"><Trash2 className="h-4 w-4"/></button></div></div>)}</div>{open&&<BrandModal brand={edit} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);qc.invalidateQueries({queryKey:["admin-brands"]})}}/>}</>}
function BrandModal({brand,onClose,onSaved}:any){const [name,setName]=useState(brand?.name||"");const [slug,setSlug]=useState(brand?.slug||"");const [slugTouched,setSlugTouched]=useState(Boolean(brand?.slug));const slugify=(v:string)=>v.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");const [file,setFile]=useState<File|null>(null);const save=useMutation({mutationFn:async()=>{if(!name.trim())throw new Error("Brand name is required");const fd=new FormData();fd.append("name",name.trim());if(slug.trim())fd.append("slug",slug.trim());if(file)fd.append("image",file);return brand?api.put(`/admin/brands/${brand.id||brand._id}`,fd):api.post("/admin/brands",fd);},onSuccess:()=>{toast.success("Brand saved");onSaved()},onError:(e:any)=>toast.error(e.message)});return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-card p-6"><h2 className="text-xl font-bold">{brand?"Edit":"Add"} Brand</h2><label className="mt-4 block text-sm font-semibold">Brand name<input value={name} onChange={e=>{const v=e.target.value;setName(v);if(!slugTouched)setSlug(slugify(v));}} className="mt-1 w-full rounded-xl border bg-background px-3 py-2"/></label><label className="mt-3 block text-sm font-semibold">Slug<input value={slug} onChange={e=>{setSlugTouched(true);setSlug(slugify(e.target.value));}} placeholder="auto-generated" className="mt-1 w-full rounded-xl border bg-background px-3 py-2"/></label><label className="mt-3 block text-sm font-semibold">Logo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border px-4 py-2">Cancel</button><button disabled={save.isPending} onClick={()=>save.mutate()} className="rounded-xl bg-primary px-4 py-2 font-bold text-primary-foreground">Save</button></div></div></div>}
