/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceAreaVerificationsRouteImport } from './routes/service-area-verifications'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MrBreadoRestaurantRouteImport } from './routes/mr-breado-restaurant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as DeliveryBoysRouteImport } from './routes/delivery-boys'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomerMessagesRouteImport } from './routes/customer-messages'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as AdminProfileRouteImport } from './routes/admin-profile'
import { Route as AdminFoodsRouteImport } from './routes/admin-foods'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersReadyForPickupRouteImport } from './routes/orders/ready-for-pickup'
import { Route as OrdersPreparingRouteImport } from './routes/orders/preparing'
import { Route as OrdersPendingRouteImport } from './routes/orders/pending'
import { Route as OrdersDeliveredRouteImport } from './routes/orders/delivered'
import { Route as OrdersCancelledRouteImport } from './routes/orders/cancelled'
import { Route as OrdersActiveRouteImport } from './routes/orders/active'
import { Route as OrdersAcceptedRouteImport } from './routes/orders/accepted'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaVerificationsRoute =
  ServiceAreaVerificationsRouteImport.update({
    id: '/service-area-verifications',
    path: '/service-area-verifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MrBreadoRestaurantRoute = MrBreadoRestaurantRouteImport.update({
  id: '/mr-breado-restaurant',
  path: '/mr-breado-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryBoysRoute = DeliveryBoysRouteImport.update({
  id: '/delivery-boys',
  path: '/delivery-boys',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMessagesRoute = CustomerMessagesRouteImport.update({
  id: '/customer-messages',
  path: '/customer-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin-profile',
  path: '/admin-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFoodsRoute = AdminFoodsRouteImport.update({
  id: '/admin-foods',
  path: '/admin-foods',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersReadyForPickupRoute = OrdersReadyForPickupRouteImport.update({
  id: '/orders/ready-for-pickup',
  path: '/orders/ready-for-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPreparingRoute = OrdersPreparingRouteImport.update({
  id: '/orders/preparing',
  path: '/orders/preparing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPendingRoute = OrdersPendingRouteImport.update({
  id: '/orders/pending',
  path: '/orders/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersDeliveredRoute = OrdersDeliveredRouteImport.update({
  id: '/orders/delivered',
  path: '/orders/delivered',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersCancelledRoute = OrdersCancelledRouteImport.update({
  id: '/orders/cancelled',
  path: '/orders/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersActiveRoute = OrdersActiveRouteImport.update({
  id: '/orders/active',
  path: '/orders/active',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersAcceptedRoute = OrdersAcceptedRouteImport.update({
  id: '/orders/accepted',
  path: '/orders/accepted',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-foods': typeof AdminFoodsRoute
  '/admin-profile': typeof AdminProfileRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/cuisine': typeof CuisineRoute
  '/customer-messages': typeof CustomerMessagesRoute
  '/customers': typeof CustomersRoute
  '/delivery-boys': typeof DeliveryBoysRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/mr-breado-restaurant': typeof MrBreadoRestaurantRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/operations': typeof OperationsRoute
  '/owners': typeof OwnersRoute
  '/payouts': typeof PayoutsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/service-area-verifications': typeof ServiceAreaVerificationsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/zones': typeof ZonesRoute
  '/orders/accepted': typeof OrdersAcceptedRoute
  '/orders/active': typeof OrdersActiveRoute
  '/orders/cancelled': typeof OrdersCancelledRoute
  '/orders/delivered': typeof OrdersDeliveredRoute
  '/orders/pending': typeof OrdersPendingRoute
  '/orders/preparing': typeof OrdersPreparingRoute
  '/orders/ready-for-pickup': typeof OrdersReadyForPickupRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-foods': typeof AdminFoodsRoute
  '/admin-profile': typeof AdminProfileRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/cuisine': typeof CuisineRoute
  '/customer-messages': typeof CustomerMessagesRoute
  '/customers': typeof CustomersRoute
  '/delivery-boys': typeof DeliveryBoysRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/mr-breado-restaurant': typeof MrBreadoRestaurantRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/operations': typeof OperationsRoute
  '/owners': typeof OwnersRoute
  '/payouts': typeof PayoutsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/service-area-verifications': typeof ServiceAreaVerificationsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/zones': typeof ZonesRoute
  '/orders/accepted': typeof OrdersAcceptedRoute
  '/orders/active': typeof OrdersActiveRoute
  '/orders/cancelled': typeof OrdersCancelledRoute
  '/orders/delivered': typeof OrdersDeliveredRoute
  '/orders/pending': typeof OrdersPendingRoute
  '/orders/preparing': typeof OrdersPreparingRoute
  '/orders/ready-for-pickup': typeof OrdersReadyForPickupRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-foods': typeof AdminFoodsRoute
  '/admin-profile': typeof AdminProfileRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/coupons': typeof CouponsRoute
  '/cuisine': typeof CuisineRoute
  '/customer-messages': typeof CustomerMessagesRoute
  '/customers': typeof CustomersRoute
  '/delivery-boys': typeof DeliveryBoysRoute
  '/foods': typeof FoodsRoute
  '/login': typeof LoginRoute
  '/mr-breado-restaurant': typeof MrBreadoRestaurantRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/operations': typeof OperationsRoute
  '/owners': typeof OwnersRoute
  '/payouts': typeof PayoutsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRoute
  '/reviews': typeof ReviewsRoute
  '/roles': typeof RolesRoute
  '/service-area-verifications': typeof ServiceAreaVerificationsRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
  '/zones': typeof ZonesRoute
  '/orders/accepted': typeof OrdersAcceptedRoute
  '/orders/active': typeof OrdersActiveRoute
  '/orders/cancelled': typeof OrdersCancelledRoute
  '/orders/delivered': typeof OrdersDeliveredRoute
  '/orders/pending': typeof OrdersPendingRoute
  '/orders/preparing': typeof OrdersPreparingRoute
  '/orders/ready-for-pickup': typeof OrdersReadyForPickupRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-foods'
    | '/admin-profile'
    | '/banners'
    | '/categories'
    | '/coupons'
    | '/cuisine'
    | '/customer-messages'
    | '/customers'
    | '/delivery-boys'
    | '/foods'
    | '/login'
    | '/mr-breado-restaurant'
    | '/notifications'
    | '/offers'
    | '/operations'
    | '/owners'
    | '/payouts'
    | '/permissions'
    | '/register'
    | '/restaurants'
    | '/reviews'
    | '/roles'
    | '/service-area-verifications'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tickets'
    | '/zones'
    | '/orders/accepted'
    | '/orders/active'
    | '/orders/cancelled'
    | '/orders/delivered'
    | '/orders/pending'
    | '/orders/preparing'
    | '/orders/ready-for-pickup'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-foods'
    | '/admin-profile'
    | '/banners'
    | '/categories'
    | '/coupons'
    | '/cuisine'
    | '/customer-messages'
    | '/customers'
    | '/delivery-boys'
    | '/foods'
    | '/login'
    | '/mr-breado-restaurant'
    | '/notifications'
    | '/offers'
    | '/operations'
    | '/owners'
    | '/payouts'
    | '/permissions'
    | '/register'
    | '/restaurants'
    | '/reviews'
    | '/roles'
    | '/service-area-verifications'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tickets'
    | '/zones'
    | '/orders/accepted'
    | '/orders/active'
    | '/orders/cancelled'
    | '/orders/delivered'
    | '/orders/pending'
    | '/orders/preparing'
    | '/orders/ready-for-pickup'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/admin-foods'
    | '/admin-profile'
    | '/banners'
    | '/categories'
    | '/coupons'
    | '/cuisine'
    | '/customer-messages'
    | '/customers'
    | '/delivery-boys'
    | '/foods'
    | '/login'
    | '/mr-breado-restaurant'
    | '/notifications'
    | '/offers'
    | '/operations'
    | '/owners'
    | '/payouts'
    | '/permissions'
    | '/register'
    | '/restaurants'
    | '/reviews'
    | '/roles'
    | '/service-area-verifications'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tickets'
    | '/zones'
    | '/orders/accepted'
    | '/orders/active'
    | '/orders/cancelled'
    | '/orders/delivered'
    | '/orders/pending'
    | '/orders/preparing'
    | '/orders/ready-for-pickup'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminFoodsRoute: typeof AdminFoodsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  BannersRoute: typeof BannersRoute
  CategoriesRoute: typeof CategoriesRoute
  CouponsRoute: typeof CouponsRoute
  CuisineRoute: typeof CuisineRoute
  CustomerMessagesRoute: typeof CustomerMessagesRoute
  CustomersRoute: typeof CustomersRoute
  DeliveryBoysRoute: typeof DeliveryBoysRoute
  FoodsRoute: typeof FoodsRoute
  LoginRoute: typeof LoginRoute
  MrBreadoRestaurantRoute: typeof MrBreadoRestaurantRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OperationsRoute: typeof OperationsRoute
  OwnersRoute: typeof OwnersRoute
  PayoutsRoute: typeof PayoutsRoute
  PermissionsRoute: typeof PermissionsRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ReviewsRoute: typeof ReviewsRoute
  RolesRoute: typeof RolesRoute
  ServiceAreaVerificationsRoute: typeof ServiceAreaVerificationsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  TicketsRoute: typeof TicketsRoute
  ZonesRoute: typeof ZonesRoute
  OrdersAcceptedRoute: typeof OrdersAcceptedRoute
  OrdersActiveRoute: typeof OrdersActiveRoute
  OrdersCancelledRoute: typeof OrdersCancelledRoute
  OrdersDeliveredRoute: typeof OrdersDeliveredRoute
  OrdersPendingRoute: typeof OrdersPendingRoute
  OrdersPreparingRoute: typeof OrdersPreparingRoute
  OrdersReadyForPickupRoute: typeof OrdersReadyForPickupRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area-verifications': {
      id: '/service-area-verifications'
      path: '/service-area-verifications'
      fullPath: '/service-area-verifications'
      preLoaderRoute: typeof ServiceAreaVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mr-breado-restaurant': {
      id: '/mr-breado-restaurant'
      path: '/mr-breado-restaurant'
      fullPath: '/mr-breado-restaurant'
      preLoaderRoute: typeof MrBreadoRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-boys': {
      id: '/delivery-boys'
      path: '/delivery-boys'
      fullPath: '/delivery-boys'
      preLoaderRoute: typeof DeliveryBoysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-messages': {
      id: '/customer-messages'
      path: '/customer-messages'
      fullPath: '/customer-messages'
      preLoaderRoute: typeof CustomerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-profile': {
      id: '/admin-profile'
      path: '/admin-profile'
      fullPath: '/admin-profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-foods': {
      id: '/admin-foods'
      path: '/admin-foods'
      fullPath: '/admin-foods'
      preLoaderRoute: typeof AdminFoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/ready-for-pickup': {
      id: '/orders/ready-for-pickup'
      path: '/orders/ready-for-pickup'
      fullPath: '/orders/ready-for-pickup'
      preLoaderRoute: typeof OrdersReadyForPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/preparing': {
      id: '/orders/preparing'
      path: '/orders/preparing'
      fullPath: '/orders/preparing'
      preLoaderRoute: typeof OrdersPreparingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/pending': {
      id: '/orders/pending'
      path: '/orders/pending'
      fullPath: '/orders/pending'
      preLoaderRoute: typeof OrdersPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/delivered': {
      id: '/orders/delivered'
      path: '/orders/delivered'
      fullPath: '/orders/delivered'
      preLoaderRoute: typeof OrdersDeliveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/cancelled': {
      id: '/orders/cancelled'
      path: '/orders/cancelled'
      fullPath: '/orders/cancelled'
      preLoaderRoute: typeof OrdersCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/active': {
      id: '/orders/active'
      path: '/orders/active'
      fullPath: '/orders/active'
      preLoaderRoute: typeof OrdersActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/accepted': {
      id: '/orders/accepted'
      path: '/orders/accepted'
      fullPath: '/orders/accepted'
      preLoaderRoute: typeof OrdersAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminFoodsRoute: AdminFoodsRoute,
  AdminProfileRoute: AdminProfileRoute,
  BannersRoute: BannersRoute,
  CategoriesRoute: CategoriesRoute,
  CouponsRoute: CouponsRoute,
  CuisineRoute: CuisineRoute,
  CustomerMessagesRoute: CustomerMessagesRoute,
  CustomersRoute: CustomersRoute,
  DeliveryBoysRoute: DeliveryBoysRoute,
  FoodsRoute: FoodsRoute,
  LoginRoute: LoginRoute,
  MrBreadoRestaurantRoute: MrBreadoRestaurantRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OperationsRoute: OperationsRoute,
  OwnersRoute: OwnersRoute,
  PayoutsRoute: PayoutsRoute,
  PermissionsRoute: PermissionsRoute,
  RegisterRoute: RegisterRoute,
  RestaurantsRoute: RestaurantsRoute,
  ReviewsRoute: ReviewsRoute,
  RolesRoute: RolesRoute,
  ServiceAreaVerificationsRoute: ServiceAreaVerificationsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  TicketsRoute: TicketsRoute,
  ZonesRoute: ZonesRoute,
  OrdersAcceptedRoute: OrdersAcceptedRoute,
  OrdersActiveRoute: OrdersActiveRoute,
  OrdersCancelledRoute: OrdersCancelledRoute,
  OrdersDeliveredRoute: OrdersDeliveredRoute,
  OrdersPendingRoute: OrdersPendingRoute,
  OrdersPreparingRoute: OrdersPreparingRoute,
  OrdersReadyForPickupRoute: OrdersReadyForPickupRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
